login: &login
  adapter: postgresql
  encoding: unicode
  username: sf
  password:
  pool: 5
  host: localhost

development:
  <<: *login
  database: sf_dev

test: &test
  <<: *login
  database: sf_test
